"""phase1 core tables

Revision ID: 0951bb2d2731
Revises: 
Create Date: 2026-08-24 19:47:43.249383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0951bb2d2731'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEMO_ACTOR_ID = '7fa528e3-07b7-5613-b90d-e89b562882a3'

AUDIT_APPEND_ONLY_TRIGGER = """
CREATE FUNCTION prevent_audit_log_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
"""

AUDIT_APPEND_ONLY_TRIGGER_DROP = """
DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs;
DROP FUNCTION IF EXISTS prevent_audit_log_mutation();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors')),
    sa.UniqueConstraint('name', name=op.f('uq_actors_name'))
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('fixture_version', sa.String(length=64), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_table('ground_truth_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opaque_source_record_id', sa.String(length=255), nullable=False),
    sa.Column('fixture_version', sa.String(length=64), nullable=True),
    sa.Column('expected_outcome', sa.String(length=64), nullable=True),
    sa.Column('expected_classification', sa.String(length=64), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ground_truth_labels')),
    sa.UniqueConstraint('opaque_source_record_id', name=op.f('uq_ground_truth_labels_opaque_source_record_id'))
    )
    op.create_table('match_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deterministic_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('expected_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('actual_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('delta_paise', sa.BigInteger(), nullable=True),
    sa.Column('rule_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_groups'))
    )
    op.create_index(op.f('ix_match_groups_batch_id'), 'match_groups', ['batch_id'], unique=False)
    op.create_index(op.f('ix_match_groups_org_id'), 'match_groups', ['org_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_org_id'), 'sources', ['org_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_webhook_events_provider_event_id'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_hypothesis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_audit_logs_actor_id_actors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_kind', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('gross_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('fee_paise', sa.BigInteger(), nullable=True),
    sa.Column('tax_paise', sa.BigInteger(), nullable=True),
    sa.Column('refund_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_transactions_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_transactions_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_transactions_source_external')
    )
    op.create_index(op.f('ix_transactions_effective_date'), 'transactions', ['effective_date'], unique=False)
    op.create_index(op.f('ix_transactions_org_id'), 'transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_transactions_source_id'), 'transactions', ['source_id'], unique=False)
    op.create_index(op.f('ix_transactions_utr'), 'transactions', ['utr'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_group_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('taxonomy', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faithfulness_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_groups.id'], name=op.f('fk_exceptions_match_group_id_match_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_exceptions_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    op.create_table('match_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_group_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('allocated_paise', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_groups.id'], name=op.f('fk_match_members_match_group_id_match_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_match_members_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_members'))
    )
    op.create_index(op.f('ix_match_members_match_group_id'), 'match_members', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_match_members_transaction_id'), 'match_members', ['transaction_id'], unique=False)

    op.execute(AUDIT_APPEND_ONLY_TRIGGER)

    op.execute(
        "INSERT INTO actors (id, name, display_name, is_demo) "
        f"VALUES ('{DEMO_ACTOR_ID}', 'demo_finance_controller', 'Demo Finance Controller', true) "
        "ON CONFLICT (name) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(AUDIT_APPEND_ONLY_TRIGGER_DROP)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_members_transaction_id'), table_name='match_members')
    op.drop_index(op.f('ix_match_members_match_group_id'), table_name='match_members')
    op.drop_table('match_members')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_transactions_utr'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_org_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_effective_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('audit_logs')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_sources_org_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_match_groups_org_id'), table_name='match_groups')
    op.drop_index(op.f('ix_match_groups_batch_id'), table_name='match_groups')
    op.drop_table('match_groups')
    op.drop_table('ground_truth_labels')
    op.drop_table('evaluation_runs')
    op.drop_table('actors')
    # ### end Alembic commands ###
